### ISSUE TITLE
VSCode not running personal init bash script at startup

### ISSUE THREAD

**Issue by pierre-lamarche** [InseeFrLab/helm-charts-datascience#31]
It seems like VSCode services do not take into account personal initialization scripts that may be specified in the configuration form. One explanation could rely on the absence of the env variable `PERSONNAL_INIT_SCRIPT` which appears in the [configuration form](https://github.com/InseeFrLab/helm-charts-datascience/blob/master/charts/vscode/values.schema.json), but not in the [deployment template](https://github.com/InseeFrLab/helm-charts-datascience/blob/master/charts/vscode/templates/deployment.yaml) (although I still do not exactly get how the system understands it has to be run at startup).

**Comment by fcomte** [comment]
You are right. I will fix that asap

**Comment by fcomte** [comment]
fixed

**Comment by pierre-lamarche** [comment]
Nice, it works well! Thanks a lot
