### ISSUE TITLE
Demander l'URL du repo Git dans la config des services Onyxia

### ISSUE THREAD

**Issue by avouacr** [InseeFrLab/helm-charts-datascience#34]
Dans la config Git à l'initialisation d'un service, le nom "Repository" est un peu trompeur (je m'y suis trompé, et d'autres aussi) : on s'attendrait à ne devoir mettre que le nom du repo ou à la limite username/repo, alors qu'il faut l'URL complète pour que ça fonctionne. 

Je propose de remplacer "Repository" par "URL Repository" pour bien indiquer l'input attendu.

**Comment by marchufschmitt** [comment]
![image](https://user-images.githubusercontent.com/62331119/141796158-08544b35-46a3-4c21-98b7-467825cc3ad5.png)
